apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: 22i1297/cartservice:44a5703
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis:6379"          # connects to our Redis database
            - name: PORT
              value: "7070"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
